version: '3'
services:
    ds4a-team23:
        build: .
        container_name: ds4a-python
        ports:
            - "8050:8050"
            - "8888:8888"
        volumes:
            - ../project:/home/jovyan/work
